### ISSUE TITLE
Warning when installing the library with composer

### ISSUE THREAD

**Issue by modir** [heimrichhannot/contao-calendar_plus#2]
After running "composer require heimrichhannot/contao-calendar_plus" I get in the output the following warnings:

```
Package heimrichhannot/contao-be_explanation is abandoned, you should avoid using it. Use heimrichhannot/contao-be_explanation-bundle instead.
Package heimrichhannot/contao-request is abandoned, you should avoid using it. Use heimrichhannot/contao-request-bundle instead.
Package heimrichhannot/contao-ajax is abandoned, you should avoid using it. Use heimrichhannot/contao-ajax-bundle instead.
Package heimrichhannot/contao-teaser is abandoned, you should avoid using it. Use heimrichhannot/contao-teaser-bundle instead.
Package heimrichhannot/contao-fieldpalette is abandoned, you should avoid using it. Use heimrichhannot/contao-fieldpalette-bundle instead.
Package heimrichhannot/contao-inserttag_download is abandoned, you should avoid using it. Use heimrichhannot/contao-inserttagcollection-bundle instead.
```
Since all of them reference to your own self written packages I would suggest that you update the dependencies of this "calendar plus" package to your new helper packages.

**Comment by koertho** [comment]
Hi, we do not develop calendar_plus further (only if needed for some legacy projects), so we won't update the modules (since their successors are bundles). You can check out our events bundle, which is kind of the spiritual successor to calendar plus.

https://github.com/heimrichhannot/contao-events-bundle

**Comment by jankout** [comment]
> Hi, we do not develop calendar_plus further (only if needed for some legacy projects), so we won't update the modules (since their successors are bundles). You can check out our events bundle, which is kind of the spiritual successor to calendar plus.
> 
> https://github.com/heimrichhannot/contao-events-bundle

Thank you for the information. Unfortunately the extension you recommend to use instead of this one does't have the same functions. I would appreciate to use this old one. Are you sure you don't want to keep developing it? That would be really pity.  

Another question: Could you tell me please where I can find the command for docents list? I would like to use it in my _event_full.html5_.

**Comment by koertho** [comment]
@jankout Please open new issues for features requests and questions. That would be easier for us to maintain. Thanks!
